services:
  api:
    container_name: backpacker-api
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 5004:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: ["blog-sql"]
    networks:
      blog-networks:
  
  blog-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=KillThemAll!!!"
    volumes:
      - "blog-volumes-api-sql:/var/opt/mssql"
    networks:
      blog-networks:
        aliases:
          - "SQLBlog"

volumes:
  blog-volumes-api-sql:

networks:
  blog-networks:
    driver: bridge
